name: SlotShare
version: '1.0'
main: com.sugar_tree.slotshare.SlotShare
api-version: 1.18
authors: [ sugar_tree ]
website: https://github.com/the-sugar-tree/SlotShare
commands:
  slotshare:
    aliases:
      - ss
    description: turn on/off Slot Sharing
    usage: /slotshare
    permission: slotshare
permissions:
  slotshare:
    default: op
    description: Allows use /slotshare